# Auth API Endpoints
# ==================
# This file contains HTTP requests for authentication-related operations.
# Use these endpoints to register, login, and logout users.

@baseUrl = http://localhost:8000/api/v1

### Register User
# Endpoint to register a new user.
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "Admin User",            
  "email": "admin@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Login - Get Token
# Endpoint to log in and retrieve an authentication token.
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password"
}

### Logout User
# Endpoint to log out the authenticated user.
POST {{baseUrl}}/logout
Authorization: Bearer 12|8KrYKK9owCmeLf2MZ7YGpX1Zy6mg7ZeRLMTQ9rqjc5989169
Accept: application/json
