version: '3.8'
services:
  laravel_app:
    build: ./docker/php
    volumes: ['./app:/var/www']
    networks: [laravel]
  nginx:
    image: nginx:alpine
    ports: ['80:80']
    volumes: ['./app:/var/www', './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf']
    networks: [laravel]
networks:
  laravel: { driver: bridge }