name: Run CMS Laravel Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: Testing

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm i

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      # - name: Update .env for MySQL
      #   run: |
      #     sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
      #     sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
      #     sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
      #     sed -i 's/DB_DATABASE=.*/DB_DATABASE=testing/' .env
      #     sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
      #     sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

      # - name: Wait for MySQL to be ready
      #   run: sleep 20

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Configure SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
        # membuat file SQLite kosong

      - name: Update .env for SQLite
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i '/DB_HOST/d' .env
          sed -i '/DB_PORT/d' .env
          sed -i '/DB_DATABASE/c\DB_DATABASE='$(pwd)'/database/database.sqlite' .env
        # overwrite DB config di .env agar pakai SQLite lokal

      - name: Run Migrations
        run: php artisan migrate --force
      
      # - name: Run Seeders
      #   run: php artisan db:seed --force

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: ./vendor/bin/phpunit